name: Manual Go Build

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'build-tui'
        type: choice
        options:
          - build-tui

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # Adjust to your Go version

      # Restore Go cache
      - name: Restore Go cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Build binaries for selected platforms
      - name: Build TUI binaries
        if: ${{ inputs.action == 'build-tui' }}
        run: |
          mkdir -p bin
          GOOS=linux GOARCH=amd64 go build -o bin/docker-stack-linux-amd64 -ldflags="-s -w" .
          GOOS=darwin GOARCH=amd64 go build -o bin/docker-stack-macos-amd64 -ldflags="-s -w" .
          GOOS=windows GOARCH=amd64 go build -o bin/docker-stack-windows-amd64.exe -ldflags="-s -w" .
          chmod +x bin/docker-stack-*  # Make binaries executable (except Windows)

      # Upload binaries as artifacts
      - name: Upload TUI binaries
        if: ${{ inputs.action == 'build-tui' }}
        uses: actions/upload-artifact@v4
        with:
          name: tui-binaries
          path: bin/
