name: Release Setup Script

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload setup.sh to release
        uses: softprops/action-gh-release@v1
        with:
          files: setup.sh
          tag_name: ${{ github.ref_name }}
